### ISSUE TITLE
Nginx 1.13: Connection issues with enabled aio

### ISSUE THREAD

**Issue by pracj3am** [kaltura/nginx-vod-module#645]
Hello. I compiled the vod module v1.18 with nginx v1.13.3 and found serveral issues if **aio is turned on** (does not matter if with or without threads).

1. If client doesn't send header `Connection: close`, i.e.
```
curl -v -o 1.ts http://127.0.0.1/hls/test.mp4/seg-1-v1-a1.ts
```
nginx fails with a segafault like `free(): invalid pointer` or `corrupted double-linked list`. In case that the client asked for the segment already with `Connection: close`, nginx fails with
```
2017/07/20 16:33:07 [emerg] 29868#29868: *9 posix_memalign(16, 45818614096680) failed (12: Cannot allocate memory) while keepalive, client: 127.0.0.1, server: 0.0.0.0:80
2017/07/20 16:33:07 [debug] 29868#29868: *9 posix_memalign: 0000000000000000:45818614096680 @16
2017/07/20 16:33:07 [debug] 29868#29868: *9 ngx_http_vod_alloc_read_buffer: failed to allocate read buffer of size 262176
2017/07/20 16:33:07 [debug] 29868#29868: *9 ngx_http_vod_run_state_machine: ngx_http_vod_process_media_frames failed 500
2017/07/20 16:33:07 [debug] 29868#29868: *9 http finalize request: -1, "�p�A�3Vp�A�3Vp�A�3V?" a:0, c:1
```
Because of this, the stream cannot be played in javascript videoplayers.

2. If client sends header `Connection: close`, i.e.
```
curl -v -o 1.ts -H "Connection: close" http://127.0.0.1/hls/test.mp4/seg-1-v1-a1.ts
```
nginx fails with `[alert] 29868#29868: *10 http request count is zero while processing frames` and thus nginx doesn't close the connection which results that some clients are waiting indefinitely (e.g. mpv or mplayer).

My config:
```
daemon on;

user www-data www-data;
error_log  /var/log/nginx/error.log debug;
pid /var/run/nginx.pid;
worker_processes 1;

events
{
}

http
{
    server {
        listen 80 default_server;
        server_name _;

        root /var/www/mp4/;
        expires 100d;

        # vod settings
        vod_segment_duration 2000; # 2s
        vod_align_segments_to_key_frames on;

        vod_mode local;
        vod_metadata_cache metadata_cache 2048m;
        vod_response_cache response_cache 256m;

        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;
        
        aio on;

        # Headers
        add_header Access-Control-Allow-Headers '*';
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
        add_header Access-Control-Allow-Origin '*';

        location /hls/ {
            alias /var/www/mp4/;
            vod hls;
        }
    }
}
```

**Comment by erankor** [comment]
Your build is most likely broken, probably the structs used by nginx-vod don't match the ones in nginx core.
Did you compile it as a static or dynamic module? If dynamic, did compile both the module and nginx core? Did you use the same parameter and sources?

**Comment by pracj3am** [comment]
I compiled it as static module. Do you mean structs of nginx? Because I
have just one nginx source files present in system.

I have also tried to compile it on two different systems (jessie and
stretch) with the same result.

**Comment by erankor** [comment]
Yes, that is what I referred to. 
Please send the commands you used to compile it

**Comment by pracj3am** [comment]
Okay, thanks

**Comment by erankor** [comment]
You didn't send the compilation commands... :) Also, you can try with our pre-compiled package

**Comment by pracj3am** [comment]
I tried, but I wasn't able to run it, since it depended on libssl 1.0.0

**Comment by pracj3am** [comment]
I created a dockerfile:

```dockerfile
FROM debian:stretch

WORKDIR ~

RUN \
    apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    build-essential ca-certificates libtool autoconf automake git wget \
    libssl1.0-dev libpcre3-dev libz-dev

RUN \
    git clone https://github.com/nginx/nginx.git && cd nginx && \
    git checkout release-1.13.3 && cd ..

RUN \
    git clone https://github.com/kaltura/nginx-vod-module.git && cd nginx-vod-module && \
    git checkout 1.18 && cd ..

RUN \
    cd nginx && \
    ./auto/configure --with-http_ssl_module --with-http_v2_module \
        --without-http_fastcgi_module --without-http_uwsgi_module \
        --without-http_scgi_module --without-http_memcached_module \
        --with-http_secure_link_module --with-http_stub_status_module \
        --with-file-aio --with-threads --add-module=../nginx-vod-module && \
    make && make install

RUN \
	mkdir -p /var/www/mp4 && cd /var/www/mp4 && \
    wget http://gl9b3vbz7de9ug96etc6.push-20.cdn77.com/bad_kingdom.mp4

RUN \
   echo "\
daemon off; \n\ 
 \n\
user www-data www-data; \n\
worker_processes 1; \n\
error_log stderr debug; \n\
 \n\
events {} \n\
 \n\
http \n\
{ \n\
    server { \n\
        listen 80 default_server; \n\
        server_name _; \n\
 \n\
        root /var/www/mp4/; \n\
        expires 100d; \n\
 \n\
        # vod settings \n\
        vod_segment_duration 2000; # 2s \n\
        vod_align_segments_to_key_frames on; \n\
 \n\
        vod_mode local; \n\
        vod_metadata_cache metadata_cache 2048m; \n\
        vod_response_cache response_cache 256m; \n\
 \n\
        open_file_cache          max=1000 inactive=5m; \n\
        open_file_cache_valid    2m; \n\
        open_file_cache_min_uses 1; \n\
        open_file_cache_errors   on; \n\
 \n\
        aio on; \n\
 \n\
        add_header Access-Control-Allow-Headers '*'; \n\
        add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range'; \n\
        add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS'; \n\
        add_header Access-Control-Allow-Origin '*'; \n\
 \n\
        location /hls/ { \n\
            alias /var/www/mp4/; \n\
            vod hls; \n\
        } \n\
    } \n\
}" > /usr/local/nginx/conf/nginx.conf

CMD /usr/local/nginx/sbin/nginx 
```

Then you can test it with
```
docker build -t nginx-vod .
docker run -p 8080:80 --rm -it nginx-vod
curl -v -o 1.ts http://127.0.0.1:8080/hls/bad_kingdom.mp4/seg-1-v1-a1.ts
```

**Comment by jessp01** [comment]
Hi @pracj3am,

I am able to reproduce the segault. @erankor or myself will look into it.
We've never tested with the 1.13 branch, only with 1.12.0 which is the stable branch at the moment.
For now, please use Nginx 1.12.0 with which this will not happen. I tested it using the same stretch container.

For everyone's benefit, here is the full backtrace:
```
#0  0x00007ffff68fe249 in malloc_consolidate (av=av@entry=0x7ffff6c20b00 <main_arena>) at malloc.c:4213
        fb = 0x7ffff6c20b18 <main_arena+24>
        maxfb = 0x7ffff6c20b50 <main_arena+80>
        p = 0x5555559c9c00
        nextp = 0x0
        unsorted_bin = 0x7ffff6c20b58 <main_arena+88>
        first_unsorted = <optimized out>
        nextchunk = 0x5555559cbe40
        size = 8768
        nextsize = 134217728
        prevsize = <optimized out>
        nextinuse = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
#1  0x00007ffff68ffdca in _int_malloc (av=av@entry=0x7ffff6c20b00 <main_arena>, bytes=bytes@entry=27696) at malloc.c:3488
        nb = 27712
        idx = 116
        bin = <optimized out>
        victim = <optimized out>
        size = <optimized out>
        victim_index = <optimized out>
        remainder = <optimized out>
        remainder_size = <optimized out>
        block = <optimized out>
        bit = <optimized out>
        map = <optimized out>
        fwd = <optimized out>
        bck = <optimized out>
        errstr = 0x0
        __func__ = "_int_malloc"
#2  0x00007ffff690090e in _int_memalign (av=av@entry=0x7ffff6c20b00 <main_arena>, alignment=alignment@entry=512, 
    bytes=bytes@entry=27137) at malloc.c:4459
        nb = 27152
        m = <optimized out>
---Type <return> to continue, or q <return> to quit---
        p = <optimized out>
        brk = <optimized out>
        newp = <optimized out>
        newsize = <optimized out>
        leadsize = <optimized out>
        remainder = <optimized out>
        remainder_size = <optimized out>
        size = <optimized out>
        __func__ = "_int_memalign"
#3  0x00007ffff690232f in _mid_memalign (alignment=512, bytes=27137, address=<optimized out>) at malloc.c:3158
        ar_ptr = 0x7ffff6c20b00 <main_arena>
        p = <optimized out>
        hook = <optimized out>
        __func__ = "_mid_memalign"
#4  0x00007ffff6903fbf in __posix_memalign (memptr=0x7fffffffe5c0, alignment=<optimized out>, size=<optimized out>) at malloc.c:5071
        mem = <optimized out>
        address = <optimized out>
        size = <optimized out>
        alignment = <optimized out>
        memptr = 0x7fffffffe5c0
#5  0x00005555555bed86 in ngx_memalign (alignment=512, size=27137, log=0x55555599cc60) at src/os/unix/ngx_alloc.c:57
        p = 0x5555559cae28
        err = 0
#6  0x0000555555586623 in ngx_pmemalign (pool=0x5555559ae510, size=27137, alignment=512) at src/core/ngx_palloc.c:258
        p = 0x5555556e50e3 <mp4_parser_get_moov_atom_info+94>
        large = 0x7fffffffe660
#7  0x000055555569570c in ngx_http_vod_alloc_read_buffer (ctx=0x5555559c9fe0, size=27137, alloc_params_index=0)
    at ./nginx-vod-module/ngx_http_vod_module.c:1052
        alloc_params = 0x5555559ca1c0
        start = 0x0
#8  0x0000555555697552 in ngx_http_vod_async_read (ctx=0x5555559c9fe0, read_req=0x7fffffffe700)
    at ./nginx-vod-module/ngx_http_vod_module.c:1770
        prefix_size = 4096
        buffer_size = 4096
---Type <return> to continue, or q <return> to quit---
        read_size = 27136
        read_offset = 0
        rc = 93824996909024
#9  0x0000555555697b77 in ngx_http_vod_read_metadata (ctx=0x5555559c9fe0) at ./nginx-vod-module/ngx_http_vod_module.c:1908
        result = {read_req = {read_offset = 40, read_size = 26834, flags = 0}, parts = 0x7fffffffdf39, part_count = 30235145480}
        read_buffer = {len = 4096, data = 0x5555559cae00 ""}
        rc = -2
#10 0x00005555556983b6 in ngx_http_vod_state_machine_parse_metadata (ctx=0x5555559c9fe0)
    at ./nginx-vod-module/ngx_http_vod_module.c:2116
        conf = 0x5555559c2330
        multipart_header = {type = 4294958972, part_count = 32767}
        cur_source = 0x7fffffffe750
        r = 0x5555559ae560
        rc = 1
        metadata_loaded = 206158430256
#11 0x000055555569ac52 in ngx_http_vod_run_state_machine (ctx=0x5555559c9fe0) at ./nginx-vod-module/ngx_http_vod_module.c:3115
        rc = 93824992717848
#12 0x000055555569b7df in ngx_http_vod_handle_read_completed (context=0x5555559c9fe0, rc=0, buf=0x0, bytes_read=4096)
    at ./nginx-vod-module/ngx_http_vod_module.c:3397
        ctx = 0x5555559c9fe0
        expected_size = 93824996910608
#13 0x000055555568e1f6 in ngx_async_read_completed_callback (ev=0x5555559ca610) at ./nginx-vod-module/ngx_file_reader.c:378
        state = 0x5555559ca478
        r = 0x5555559ae560
        c = 0x5555559cf690
        aio = 0x5555559ca5a8
        bytes_read = 4096
        rc = 0
#14 0x00005555555caee7 in ngx_file_aio_event_handler (ev=0x5555559ca610) at src/os/unix/ngx_linux_aio_read.c:147
        aio = 0x5555559ca5a8
#15 0x00005555555b9848 in ngx_event_process_posted (cycle=0x55555599d1b0, posted=0x55555596f540 <ngx_posted_events>)
    at src/event/ngx_event_posted.c:33
        q = 0x5555559ca660
        ev = 0x5555559ca610
---Type <return> to continue, or q <return> to quit---
#16 0x00005555555b70b9 in ngx_process_events_and_timers (cycle=0x55555599d1b0) at src/event/ngx_event.c:259
        flags = 1
        timer = 75000
        delta = 0
#17 0x00005555555c5536 in ngx_single_process_cycle (cycle=0x55555599d1b0) at src/os/unix/ngx_process_cycle.c:309
        i = 72
#18 0x000055555558222c in main (argc=3, argv=0x7fffffffed18) at src/core/nginx.c:372
        b = 0x0
        log = 0x55555595c0a0 <ngx_log>
        i = 0
        cycle = 0x55555599d1b0
        init_cycle = {conf_ctx = 0x0, pool = 0x55555599cbe0, log = 0x55555595c0a0 <ngx_log>, new_log = {log_level = 0, file = 0x0, 
            connection = 0, disk_full_time = 0, handler = 0x0, data = 0x0, writer = 0x0, wdata = 0x0, action = 0x0, next = 0x0}, 
          log_use_stderr = 0, files = 0x0, free_connections = 0x0, free_connection_n = 0, modules = 0x0, modules_n = 0, 
          modules_used = 0, reusable_connections_queue = {prev = 0x0, next = 0x0}, reusable_connections_n = 0, listening = {
            elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, 
            pool = 0x0}, config_dump = {elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0}, config_dump_rbtree = {root = 0x0, 
            sentinel = 0x0, insert = 0x0}, config_dump_sentinel = {key = 0, left = 0x0, right = 0x0, parent = 0x0, color = 0 '\000', 
            data = 0 '\000'}, open_files = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, 
          shared_memory = {last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0, pool = 0x0}, 
          connection_n = 0, files_n = 0, connections = 0x0, read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {
            len = 32, data = 0x7fffffffef00 "/usr/local/nginx/conf/nginx.conf"}, conf_param = {len = 0, data = 0x0}, conf_prefix = {
            len = 22, data = 0x7fffffffef00 "/usr/local/nginx/conf/nginx.conf"}, prefix = {len = 12, 
            data = 0x5555556f56ae "/opt/nginx1/"}, lock_file = {len = 0, data = 0x0}, hostname = {len = 0, data = 0x0}}
        cd = 0x5555556f48c0 <__libc_csu_init>
        ccf = 0x55555599ee38

```

**Comment by pracj3am** [comment]
You're right. At 1.12.0 (1.11.13) both problems I reported disappear. Thanks!

**Comment by pracj3am** [comment]
I found that it is cause by this commit https://github.com/nginx/nginx/commit/d1d48ed8448e24ef5297bb37387544ad241591fe which is a part of 1.13.1 release.

**Comment by erankor** [comment]
@pracj3am, thank you for reporting this issue, and for taking the time to trace the specific commit that caused it. I posted this issue in nginx-devel mailing list and looking forward to their reply.

**Comment by code5381** [comment]
Thank you very much! I use v1.12.0 and everything works fine. :)

**Comment by erankor** [comment]
Support for nginx 1.13 was merged into master - https://github.com/kaltura/nginx-vod-module/pull/762
