### ISSUE TITLE
Tests fail. How to properly run them?

### ISSUE THREAD

**Issue by btseytlin** [kaltura/nginx-vod-module#821]
Hello.
I am in process of making a slight addition to nginx-vod-module.
I am absolutely confused on how to run tests.
To streamline building and testing I build the module in docker. Here's the `Dockerfile`:
```
FROM centos:7

RUN yum groupinstall -y 'Development Tools'
RUN yum install -y epel-release
RUN yum install -y wget gcc perl perl-devel perl-ExtUtils-Embed libxslt libxslt-devel libxml2 libxml2-devel gd gd-devel GeoIP GeoIP-devel
#Get nginx sources
RUN wget http://nginx.org/download/nginx-1.13.4.tar.gz && tar zxf nginx-1.13.4.tar.gz
# PCRE, zlib, openssl
RUN wget https://ftp.pcre.org/pub/pcre/pcre-8.40.tar.gz && mkdir -p /opt/local/pcre && tar xzvf pcre-8.40.tar.gz -C /opt/local/pcre && \
    wget https://www.zlib.net/zlib-1.2.11.tar.gz && mkdir -p /opt/local/zlib && tar xzvf zlib-1.2.11.tar.gz -C /opt/local/zlib && \
    wget https://www.openssl.org/source/openssl-1.1.0f.tar.gz && mkdir -p /opt/local/openssl && tar xzvf openssl-1.1.0f.tar.gz -C /opt/local/openssl
WORKDIR nginx-1.13.4

RUN yum install -y python-pip gmp python-devel && \
    pip install pycryptodome construct[extras]==2.5.3 python-kaltura


RUN mkdir -p /var/log/cache/nginx/client_temp /var/log/cache/nginx/proxy_temp /var/log/cache/nginx/fastcgi_temp /var/log/cache/nginx/uwsgi_temp /var/log/cache/nginx/scgi_temp /var/log/nginx
RUN touch /var/log/nginx/error.log
RUN touch /var/log/nginx/access.log
COPY . /src/nginx-vod-module
RUN ./configure --add-module=/src/nginx-vod-module --with-debug \
        --with-pcre=/opt/local/pcre/pcre-8.40 \
        --with-zlib=/opt/local/zlib/zlib-1.2.11 \
        --with-openssl=/opt/local/openssl/openssl-1.1.0f \
        --prefix=/etc/nginx \
        --conf-path=/src/nginx-vod-module/test/nginx.conf \
        --sbin-path=/sbin/nginx \
        --error-log-path=/var/log/nginx/error.log \
        --http-log-path=/var/log/nginx/access.log \
        --pid-path=/var/log/run/nginx.pid \
        --lock-path=/var/log/run/nginx.lock \
        --http-client-body-temp-path=/var/log/cache/nginx/client_temp \
        --http-proxy-temp-path=/var/log/cache/nginx/proxy_temp \
        --http-fastcgi-temp-path=/var/log/cache/nginx/fastcgi_temp \
        --http-uwsgi-temp-path=/var/log/cache/nginx/uwsgi_temp \
        --http-scgi-temp-path=/var/log/cache/nginx/scgi_temp \
        --with-http_ssl_module \
        --with-http_realip_module \
        --with-http_addition_module \
        --with-http_sub_module \
        --with-http_dav_module \
        --with-http_flv_module \
        --with-http_mp4_module \
        --with-http_gunzip_module \
        --with-http_gzip_static_module \
        --with-http_random_index_module \
        --with-http_secure_link_module \
        --with-http_stub_status_module \
        --with-http_auth_request_module \
        --with-mail \
        --with-mail_ssl_module \
        --with-file-aio \
        --with-ipv6 \
	    --with-threads \
        --with-cc-opt="-O3"

RUN make && make install

ENV NGX_ROOT=nginx-1.13.4
ENV VOD_ROOT=/src/nginx-vod-module

WORKDIR /src/nginx-vod-module
CMD /usr/sbin/nginx && python2 /src/nginx-vod-module/test/main.py
```

My issues:
1. I had to collect python requirements for tests manually from test files, and some are still invalid (e.g. Kaltura client is of invalid version and I have no idea which is the right one).
2. I had to manually fill the `.template` files, I am not sure how to do it properly. There is no description how the templates should be filled. 
3. Most tests fail.
E.g.:
```
vod_module_1  | Traceback (most recent call last):
vod_module_1  |   File "/src/nginx-vod-module/test/main.py", line 1040, in <module>
vod_module_1  | Running suite MainTestSuite
vod_module_1  |   Running suite DrmTestSuite
vod_module_1  |     Running suite MemoryUpstreamTestSuite
vod_module_1  |       Running testBadContentLength
vod_module_1  | http://localhost:8001/tremote/edash/p/123/sp/123/serveFlavor/entryId/123/v/123/flavorId/123/rand/539152/manifest.mpd
vod_module_1  |       Running testBadStatusLine
vod_module_1  |     MainTestSuite().run()
vod_module_1  |   File "/src/nginx-vod-module/test/test_base.py", line 108, in run
vod_module_1  |     self.runChildSuites()
vod_module_1  |   File "/src/nginx-vod-module/test/main.py", line 1029, in runChildSuites
vod_module_1  |     DrmTestSuite(NGINX_REMOTE).run()
vod_module_1  |   File "/src/nginx-vod-module/test/test_base.py", line 108, in run
vod_module_1  |     self.runChildSuites()
vod_module_1  |   File "/src/nginx-vod-module/test/main.py", line 1005, in runChildSuites
vod_module_1  |     suite.run()
vod_module_1  |   File "/src/nginx-vod-module/test/test_base.py", line 120, in run
vod_module_1  |     getattr(self, curFunc)()
vod_module_1  |   File "/src/nginx-vod-module/test/main.py", line 702, in testBadStatusLine
vod_module_1  |     self.logTracker.assertContains('upstream sent no valid HTTP/1.0 header')
vod_module_1  |   File "/src/nginx-vod-module/test/test_base.py", line 90, in assertContains
vod_module_1  |     assert(self.contains(logLine))
vod_module_1  | AssertionError
```

What's the proper workflow to run tests?
Is there a way to automatically fill the templates with proper params?

**Comment by erankor** [comment]
First of all, I'd say that I didn't invest much/any effort on making the tests easily run-able outside the scope of Kaltura. Not saying it's a bad idea, it just wasn't high enough priority for me. The most significant test that I run on every release is a comparison of millions of requests between the new and previous release (in most releases, 99% of the requests are not expected to change), and this test can't be run anyway without access to our huge video library.

Regarding the specific questions -
1. Kaltura client is needed only for one test (setup/validate_test_entries.py) and this test requires setting up a Kaltura server, so I wouldn't bother with it. It probably makes sense to detach this test from the Kaltura backend, and have 'setup' generate local files instead of uploading to Kaltura.
2. Templates - there is no automatic process for setting them up, there are a few comments in main_params for example. 
3. A bit hard to say from this log what is the problem, but in general, main.py expects to have an nginx server running on localhost with the nginx.conf that is committed to the test folder. Nginx has to be compiled with debug logs enabled, since some tests look at the log to make sure the desired condition was achieved.
