### ISSUE TITLE
Set HLS VIDEO-RANGE attribute for HDR

### ISSUE THREAD

**Issue by ddunkin** [kaltura/nginx-vod-module#885]
`EXT-X-STREAM-INF` and `EXT-X-I-FRAME-STREAM-INF` tags must set the `VIDEO-RANGE` attribute if any variant is HDR.

https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-02#section-4.4.4.2

**Comment by erankor** [comment]
Do you have sample files for the 2 formats?

**Comment by ddunkin** [comment]
Sample SDR/HDR videos? Here are a couple: https://drive.google.com/drive/folders/10w0p3k4KhRdW-LSvVwDRV5IbW2tUFZHc?usp=sharing

TransferCharacteristics code points referenced are:

| code point | name |
| --- | --- |
| 1 | BT.709 |
| 16 | SMPTE ST 2084 |
| 18 | Hybrid Log-Gamma |

https://github.com/FFmpeg/FFmpeg/blob/be0b77e6e83b61c2da338201b5ddfae1c9acedc5/libavutil/pixfmt.h#L448-L475

**Comment by erankor** [comment]
Try this pull - #886 
I tested only the first file, google Drive is hardly working for me :(

**Comment by ddunkin** [comment]
It works for the bt709 file, but crashes (sig 11) for the smpte2084 file.

**Comment by erankor** [comment]
Is that the Exodus video there? I tried it and didn't see a crash. 
Which URL is crashing? Can you share a stack trace of the crash?

**Comment by ddunkin** [comment]
Here's the backtrace. I'm using an HTTP backend, not local files, if that makes a difference. This was from the Exodus video.

```
(gdb) backtrace
#0  0x000055e33aae8906 in hevc_parser_parse_extra_data (
    context=0x55e33b76bcf0, extra_data=0x7ffea6ae18b0,
    nal_packet_size_length=0x0, min_packet_size=0x0)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/vod/hevc_parser.c:1343
#1  0x000055e33aaf8f72 in media_format_finalize_track (
    request_context=0x55e33b7a46b8, parse_type=39846061,
    media_info=0x7ffea6ae1868)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/vod/media_format.c:80
#2  0x000055e33ab1a8cf in mp4_parser_process_moov_atom_callback (
    ctx=0x7ffea6ae1b60, atom_info=0x7ffea6ae1af0)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/vod/mp4/mp4_parser.c:2799
#3  0x000055e33ab1c7b5 in mp4_parser_parse_atoms (
    request_context=0x55e33b7a46b8, buffer=0x7fef45af535d "",
    buffer_size=34393, validate_full_atom=1,
    callback=0x55e33ab1a037 <mp4_parser_process_moov_atom_callback>,
    context=0x7ffea6ae1b60)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/vod/mp4/mp4_parser_base.c:81
#4  0x000055e33ab1aedc in mp4_parser_parse_basic_metadata (
    request_context=0x55e33b7a46b8, parse_params=0x7ffea6ae1c70,
    metadata_parts=0x55e33b75e428, metadata_part_count=2,
    result=0x55e33b7a4a70)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/vod/mp4/mp4_parser.c:2937
#5  0x000055e33aac3c5f in ngx_http_vod_parse_metadata (ctx=0x55e33b7a46b8,
    fetched_from_cache=0)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/ngx_http_vod_module.c:1708
#6  0x000055e33aac5513 in ngx_http_vod_state_machine_parse_metadata (
    ctx=0x55e33b7a46b8)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/ngx_http_vod_module.c:2274
#7  0x000055e33aac8205 in ngx_http_vod_run_state_machine (ctx=0x55e33b7a46b8)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/ngx_http_vod_module.c:3400
#8  0x000055e33aac8e32 in ngx_http_vod_handle_read_completed (
    context=0x55e33b7a46b8, rc=0, buf=0x55e33b76a708, bytes_read=34401)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/ngx_http_vod_module.c:3716
#9  0x000055e33aab72a7 in ngx_child_request_wev_handler (r=0x55e33b7576b0)
    at /usr/local/src/openresty-1.11.2.5/../nginx-vod-module-9cc161659407b09271a00a591268ce77bd910104/ngx_child_http_request.c:235
#10 0x000055e33a971891 in ngx_http_run_posted_requests (c=0x7fef45c77200)
    at src/http/ngx_http_request.c:2235
#11 0x000055e33a98a156 in ngx_http_upstream_handler (ev=0x55e33b773f80)
    at src/http/ngx_http_upstream.c:1130
#12 0x000055e33a93cdad in ngx_event_process_posted (cycle=0x55e33b6c3fb0,
    posted=0x55e33add9770 <ngx_posted_events>)
    at src/event/ngx_event_posted.c:34
#13 0x000055e33a93a2f7 in ngx_process_events_and_timers (cycle=0x55e33b6c3fb0)
    at src/event/ngx_event.c:269
#14 0x000055e33a94a03d in ngx_worker_process_cycle (cycle=0x55e33b6c3fb0,
    data=0x1) at src/os/unix/ngx_process_cycle.c:821
#15 0x000055e33a946184 in ngx_spawn_process (cycle=0x55e33b6c3fb0,
    proc=0x55e33a949f42 <ngx_worker_process_cycle>, data=0x1,
    name=0x55e33ab2fb45 "worker process", respawn=-3)
    at src/os/unix/ngx_process.c:198
#16 0x000055e33a948b5b in ngx_start_worker_processes (cycle=0x55e33b6c3fb0,
    n=2, type=-3) at src/os/unix/ngx_process_cycle.c:398
#17 0x000055e33a947ef6 in ngx_master_process_cycle (cycle=0x55e33b6c3fb0)
    at src/os/unix/ngx_process_cycle.c:135
#18 0x000055e33a905c2e in main (argc=1, argv=0x7ffea6ae2478)
    at src/core/nginx.c:367

**Comment by erankor** [comment]
Thanks, fixed (pushed to the same branch)
I think I was on the wrong branch when I tested this video earlier...

**Comment by ddunkin** [comment]
This works for me now. Thanks!

**Comment by erankor** [comment]
Merged, thanks
